<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        //cách 1
        // testAsync= async (id)=>{
        //     let response= await fetch(`https://jsonplaceholder.typicode.com/posts/${id}`)
        //     if(response && response.status!==200){
        //         throw new Error('Something wrongs! with the code:' + response.status)
        //         //reject
        //     }
        //     let data= await response.json();
        //     return data;
        // }
        // testAsync(1).then(data=>{
        //     console.log(data);
        // })
        // .catch(data=>{
        //     console.log(data.message);
        // })

        //cách 2
        testAsync= async (id)=>{
            try{
                let response= await fetch(`https://jsonplaceholder.typicode.com/posts/${id}`)
                let data= await response.json();
                //cách này là sẽ ném lỗi vào trong catch(exception)
                if(response && response.status!=200){
                    throw new Error('Something wrongs!')
                }
                return data;
            }catch(e){
                //nhận lỗi từ new Error()
                console.log(e.message);
            }
        }
        testAsync('1').then(data=>{
            console.log(data);
        })
    </script>
</body>

</html>